name: KaasCore
version: '1.0'
main: bas.pennings.kaasCore.KaasCore
api-version: '1.21'
load: STARTUP
authors: [ Bas Pennings ]
description: Minecraft Java 1.21.5 Maven plugin exclusively made for the KaasLandMC Minecraft server.
website: https://github.com/Bazzeman/KaasCore
